
object Project {
    const val CoreAndroid = ":CoreAndroid"
    const val CoreCompose = ":CoreCompose"
    const val WordGroupScreen = ":WordGroupScreen"
    const val CreateWordGroupScreen = ":CreateWordGroupScreen"
    const val Database = ":Database"
    const val ViewGroupWordsScreen = ":ViewGroupWordsScreen"
    const val EditWordScreen = ":EditWordScreen"
    const val TTSManager = ":TTSManager"
    const val BottomBarScreen = ":BottomBarScreen"
    const val TrainingActionsScreen = ":TrainingActionsScreen"
    const val WordTranslateTrainingScreen = ":WordTranslateTrainingScreen"
    const val SettingsScreen = ":SettingsScreen"
    const val LanguageIndicator = ":LanguageIndicator"
    const val WordByEarTrainingScreen = ":WordByEarTrainingScreen"
    const val BaseTrainingComponents = ":BaseTrainingComponents"
    const val CreateBackupScreen = ":CreateBackupScreen"
    const val ArchiverCreator = ":ArchiverCreator"
    const val BackupConverter = ":BackupConverter"
}